services:
  app:
    env_file:
      - .env.dev
    image: test
    command: npm run dev:docker
    ports:
      - 127.0.0.1:5000:8080
    volumes:
      - type: bind
        source: src
        target: /express-docker/src
      - type: bind
        source: package.json
        target: /express-docker/package.json
