# Fetching the minified node image on apline linux
FROM node:slim

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /express-docker

COPY package*.json ./ 

# Installing dependencies
RUN npm install

# Copying all the src files 
COPY /src ./src

# Start the application with node
CMD [ "npm", "run", "dev"]

# Exposing server port
EXPOSE 5000